export default {
  GET_TOKEN: 'get-token',
  WRITE_TOKEN: 'write-token',
  GET_NAVBAR: 'get-navbar',
  GET_CATEGORY: 'get-category',
  GET_CATEGORY_RECOMMENDED: 'get-category-recommended',
  GET_ARTICLE: 'get-article',
  GET_HOME: 'get-home',
  CATEGORY_PARAMS: 'category-params',
  CLEAR_DATA: 'clear-data',
  FULFILLED: '_FULFILLED',
  REJECTED: '_REJECTED',
  PENDING: '_PENDING',

  //

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT'
};
