export default {
  GET_TOKEN: 'get-token',
  WRITE_TOKEN: 'write-token',
  GET_NAVBAR: 'get-navbar',
  GET_CATEGORY: 'get-category',
  GET_CATEGORY_RECOMMENDED: 'get-category-recommended',
  GET_ARTICLE: 'get-article',
  GET_HOME: 'get-home',
  CATEGORY_PARAMS: 'category-params',
  CLEAR_DATA: 'clear-data',
  FULFILLED: '_FULFILLED',
  REJECTED: '_REJECTED',
  PENDING: '_PENDING',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_ERROR: 'ALERT_ERROR',
  ALERT_CLEAR: 'ALERT_CLEAR'
};
